version: '3'

services:
  nginx_consultswap:
    image: nginx:stable-alpine
    container_name: nginx_consultswap
    ports:
      - "80:80"
    volumes:
      - ../consultswap:/var/www/consultswap:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - consultswap
      - db_consultswap
    networks:
      cswapnet:
        aliases:
          - consultswap.local


  db_consultswap:
    image: mariadb:10.5.8
    container_name: db_consultswap
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - cswapnet

  consultswap:
    build:
      context: ../consultswap
      dockerfile: Dockerfile
    container_name: consultswap
    volumes:
      - ../consultswap:/var/www/consultswap
    ports:
      - "9000:9000"
    networks:
      - cswapnet

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    container_name: redis
#    volumes:
#      - ./config/redis.conf:/redis.conf
#    command: [ "redis-server", "/redis.conf" ]
#    networks:
#      - net


networks:
  cswapnet:

